name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests and generate coverage report
        run: ./gradlew test jacocoTestReport

      - name: List coverage report directory
        run: ls -la app/build/reports/jacoco/test

      - name: Check coverage report file
        run: |
          if [ ! -f app/build/reports/jacoco/test/jacocoTestReport.xml ]; then
            echo "Coverage report not found!"
            exit 1
          fi

      - name: Publish code coverage to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: ./gradlew jacocoTestReport
          coverageLocations: ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml
          prefix: app/src/main/java
          debug: true
